// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReColhe.API.Infrastructure;

#nullable disable

namespace ReColhe.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReColhe.Domain.Entidades.ApoioReclamacao", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ReclamacaoId")
                        .HasColumnType("int");

                    b.Property<int>("ApoioReclamacaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataApoio")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UsuarioId", "ReclamacaoId");

                    b.ToTable("ApoioReclamacoes");
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmpresaId"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailContato")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefoneContato")
                        .HasColumnType("longtext");

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            EmpresaId = 1,
                            Cnpj = "00.000.000/0001-00",
                            EmailContato = "contato@empresa.com",
                            NomeFantasia = "Empresa Teste",
                            TelefoneContato = "99999-9999"
                        });
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.Notificacao", b =>
                {
                    b.Property<int>("NotificacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificacaoId"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NotificacaoId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.Pev", b =>
                {
                    b.Property<int>("PevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PevId"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("HorarioFuncionamento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10, 8)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11, 8)");

                    b.Property<string>("Materiais")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PevId");

                    b.ToTable("Pevs");
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.Reclamacao", b =>
                {
                    b.Property<int>("ReclamacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReclamacaoId"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReclamacaoId");

                    b.ToTable("Reclamacoes");
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.TipoUsuario", b =>
                {
                    b.Property<int>("TipoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TipoUsuarioId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TipoUsuarioId");

                    b.ToTable("TiposUsuario");

                    b.HasData(
                        new
                        {
                            TipoUsuarioId = 1,
                            Nome = "Comum"
                        },
                        new
                        {
                            TipoUsuarioId = 2,
                            Nome = "Colaborador"
                        });
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.UsuarioNotificacao", b =>
                {
                    b.Property<int>("UsuarioNotificacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioNotificacaoId"));

                    b.Property<bool>("Lida")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NotificacaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioNotificacaoId");

                    b.HasIndex("NotificacaoId");

                    b.ToTable("UsuarioNotificacoes");
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.UsuarioPevFavorito", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PevId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAdicao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UsuarioId", "PevId");

                    b.HasIndex("PevId");

                    b.ToTable("UsuarioPevFavoritos");
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.Usuario", b =>
                {
                    b.HasOne("ReColhe.Domain.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("ReColhe.Domain.Entidades.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.UsuarioNotificacao", b =>
                {
                    b.HasOne("ReColhe.Domain.Entidades.Notificacao", null)
                        .WithMany("UsuarioNotificacoes")
                        .HasForeignKey("NotificacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.UsuarioPevFavorito", b =>
                {
                    b.HasOne("ReColhe.Domain.Entidades.Pev", "Pev")
                        .WithMany("UsuariosFavoritos")
                        .HasForeignKey("PevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReColhe.Domain.Entidades.Usuario", "Usuario")
                        .WithMany("PevFavoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pev");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.Notificacao", b =>
                {
                    b.Navigation("UsuarioNotificacoes");
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.Pev", b =>
                {
                    b.Navigation("UsuariosFavoritos");
                });

            modelBuilder.Entity("ReColhe.Domain.Entidades.Usuario", b =>
                {
                    b.Navigation("PevFavoritos");
                });
#pragma warning restore 612, 618
        }
    }
}
